config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  get "sessions/new"
  get "pages/help"
  root "pages#index"

  get    "/login",  to:"sessions#new"
  post   "/login",  to:"sessions#create"
  delete "/logout", to:"sessions#destroy"

  resources :users
  resources :topics

  get "favorites/index"
  post "/favorites", to:"favorites#create"
  delete "/favorites", to:"favorites#destroy"


  get "comments/index"
  get "comments/new"
  post "/comments", to:"comments#create"

  root "rooms#show"
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates :user_id, presence: true
  validates :topic_id, presence: true

  belongs_to :user
  belongs_to :topic
end

app/models/message.rb
class Message < ApplicationRecord
    after_create_commit { MessageBroadcastJob.perform_later self }

    belongs_to :user
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true

  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :comments
  has_many :comment_users, through: :comments, source: "user"
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: "user"
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,presence:true,length: { in: 1..15 },uniqueness: { case_sensitive: false }
  validates :email,presence:true,confirmation: true,uniqueness: { case_sensitive: false },
            length: { maximum: 255 },format:{with:/[A-Za-z0-9._+]+@[A-Za-z]+.[A-Za-z]/i}
  validates :password_confirmation, presence: true
  validates :password, presence: true, format: { with:  /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,16}\z/i }

  has_secure_password
  has_many :topics
  has_many :comments
  has_many :comment_user, through: :comments, source: "topic"
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: "topic"
  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success,:info,:warning,:danger
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # def index
  #   @comment_topics = current_user.comment_user
  # end

  def new
    @comment = Comment.new
    @comment.topic_id = params[:topic_id]
    @comment.user_id = session[:user_id]
    @topics = Topic.find_by(id: params[:topic_id])
  end

  def create
    @comment = current_user.comments.new(comment_params)

    if @comment.save
      redirect_to topics_path, success: "コメントしました"
    else
      redirect_to comments_new_path, danger: "コメント投稿に失敗しました"
    end
  end

    private
  def comment_params
    params.require(:comment).permit(:user_id, :topic_id, :content)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def index
      @favorite_topics = current_user.favorite_topics
  end

  def create
    favorite = Favorite.new
    favorite.user_id = current_user.id
    favorite.topic_id = params[:topic_id]

    if favorite.save
      redirect_to topics_path, success: "お気に入りに登録しました"
    else
      redirect_to topics_path, danger: "お気に入りの登録に失敗しました"
    end
  end

  def destroy
      favorite = Favorite.find_by(user_id: current_user.id, topic_id: params[:topic_id])

      if favorite.destroy
        redirect_to topics_path, success: "お気に入りを解除しました"
      else
        redirect_to topics_path, danger: "お気に入りの解除に失敗しました"
      end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def help
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @messages = Message.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user=User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to topics_path, success: "ログインに成功しました"
    else
      flash.now[:danger]= "ログインに失敗しました"
      render:new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: "ログアウトしました"
  end

private
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user=nil
  end

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @q = Topic.ransack(params[:q])
    @topics = @q.result 
  end

  def new
    @topic=Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      redirect_to topics_path, success: "投稿に成功しました"
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  def destroy
      topic = Topic.find_by(id: params[:id])

      if topic.destroy
        redirect_to topics_path, success: "投稿を削除しました"
      else
        redirect_to topics_path, danger: "投稿の削除に失敗しました"
      end
  end

      private
    def topic_params
      params.require(:topic).permit(:image, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      redirect_to topics_path,success: "登録が完了しました"
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
end

  private
  def log_in(user)
    session[:user_id] = user.id
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @comment.each do |comment| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <% if !topic.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                 <span class="fa fa-heart like-btn"></span>
              <% end %>
            <% else %>
                <%= link_to favorites_path(topic_id: topic.id),method: :delete do %>
                <span class="fa fa-heart like-btn-unlike"></span>
                <% end %>
            <% end %>
            ：<%= topic.favorites.count %>
                <%= link_to comments_new_path(topic_id: topic.id), method: :get do %>
                <span class="far fa-comment comment"></span>
                <% end %>
                <%= link_to topics_path(topic_id: topic.id), method: :delete do %>
                <span class="far fa-trash-alt trash"></span>
                <% end %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/new.html.erb
<div class="topic-index-wrapper">
  <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= @topics.user.name %>
            </h2>
            <%= image_tag @topics.image.url %>
          <p class="topic-text">
            <%= @topics.description %>
          </p>
            <%= form_for @comment do |f| %>
              <%= f.hidden_field :topic_id %>
              <%= f.hidden_field :user_id %>
              <div class="form-group">
                <%= f.text_area :content, class: 'form-control' %>
              </div>
              <%= f.submit 'コメント投稿', class: 'btn btn-black btn-block' %>
            <% end %>
          </div>
        </div>
      </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <% if !topic.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                 <span class="fa fa-heart like-btn"></span>
              <% end %>
            <% else %>
                <%= link_to favorites_path(topic_id: topic.id),method: :delete do %>
                <span class="fa fa-heart like-btn-unlike"></span>
                <% end %>
            <% end %>
            <%= @likes_count %>
                <%= link_to comments_new_path(topic_id: topic.id), method: :get do %>
                <span class="far fa-comment comment"></span>
                <% end %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/rooms/show.html.erb
<div class="chat">
  <h1>Chat room</h1>

  <div id="messages">
    <%= render @messages %>
  </div>

  <form>
    <label>Say something:</label><br>
    <input type="text" data-behavior="room_speaker">
  </form>
</div>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <div class="input-group">
      <%= search_form_for @q, url: topics_path do |f| %>
        <div><%= f.text_field :user_name_cont ,placeholder: 'ユーザー名', class: 'form-control' %></div>
        <div><%= f.submit ("検索") , class: 'btn btn-default'%></div>
      <% end %>
    </div>
  </div>
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
              <% if !topic.favorite_users.include?(current_user) %>
                <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                   <span class="fa fa-heart like-btn"></span>
                <% end %>
              <% else %>
                <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                  <span class="fa fa-heart like-btn-unlike"></span>
                <% end %>
              <% end %>
              :<%= topic.favorites.count %>
                <%= link_to comments_new_path(topic_id: topic.id), method: :get do %>
                  <span class="far fa-comment comment"></span>
                <% end %>
                <%= link_to topic_path(topic.id), method: :delete do %>
                  <span class="far fa-trash-alt trash"></span>
                <% end %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
            <h4 class="h4">コメント</h4>
            <div>
              <% topic.comments.each do |comment| %>
              <p>
                <%= comment.user.name %>: <%= comment.content %>
              </p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>
          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
        <% if logged_in? %>
          <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
        <%end%>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-dffset-4 col-md-4 users-new-container">
        <h1 class="text-container text-white">Sign up</h1>
        <%= form_for @user do |f| %>
        <div class="form-group">
          <%= f.label :name, class:"text-white" %>
          <%= f.text_field :name, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :email, class:"text-white" %>
          <%= f.text_field :email, class:"form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password, class:"text-white" %>
          <%= f.password_field :password, class:"form-control", placeholder:"アルファベットを含む8~16文字" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, class:"text-white" %>
          <%= f.password_field :password_confirmation, class:"form-control" %>
        </div>

        <%= f.submit "登録",class:"btn-block btn-white" %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>