config/routes.rb
Rails.application.routes.draw do
  get 'rooms/show'
  get "sessions/new"
  get "pages/help"
  root "pages#index"

  get    "/login",  to:"sessions#new"
  post   "/login",  to:"sessions#create"
  delete "/logout", to:"sessions#destroy"

  resources :users
  resources :topics

  get "favorites/index"
  post "/favorites", to:"favorites#create"
  delete "/favorites", to:"favorites#destroy"


  get "comments/index"
  get "comments/new"
  post "/comments", to:"comments#create"

  root "rooms#show"
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :topic
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  validates :user_id, presence: true
  validates :topic_id, presence: true

  belongs_to :user
  belongs_to :topic
end

app/models/message.rb
class Message < ApplicationRecord
    after_create_commit { MessageBroadcastJob.perform_later self }

    belongs_to :user
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :user_id, presence: true
  validates :description, presence: true
  validates :image, presence: true

  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :comments
  has_many :comment_users, through: :comments, source: "user"
  has_many :favorites
  has_many :favorite_users, through: :favorites, source: "user"
end

app/models/user.rb
class User < ApplicationRecord
  validates :name,presence:true,length: { in: 1..15 },uniqueness: { case_sensitive: false }
  validates :email,presence:true,confirmation: true,uniqueness: { case_sensitive: false },
            length: { maximum: 255 },format:{with:/[A-Za-z0-9._+]+@[A-Za-z]+.[A-Za-z]/i}
  validates :password_confirmation, presence: true
  validates :password, presence: true, format: { with:  /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]{8,16}\z/i }

  has_secure_password
  has_many :topics
  has_many :comments
  has_many :comment_user, through: :comments, source: "topic"
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: "topic"
  has_many :messages
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # def index
  #   @comment_topics = current_user.comment_user
  # end

  def new
    @comment = Comment.new
    @comment.topic_id = params[:topic_id]
    @comment.user_id = session[:user_id]
    @topics = Topic.find_by(id: params[:topic_id])
  end

  def create
    @comment = current_user.comments.new(comment_params)

    if @comment.save
      redirect_to topics_path, success: "コメントしました"
    else
      redirect_to comments_new_path, danger: "コメント投稿に失敗しました"
    end
  end

    private
  def comment_params
    params.require(:comment).permit(:user_id, :topic_id, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def help
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def show
    @messages = Message.all
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user=User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to topics_path, success: "ログインに成功しました"
    else
      flash.now[:danger]= "ログインに失敗しました"
      render:new
    end
  end

  def destroy
    log_out
    redirect_to root_url, info: "ログアウトしました"
  end

private
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
    @current_user=nil
  end

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @q = Topic.ransack(params[:q])
    @topics = @q.result 
  end

  def new
    @topic=Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      redirect_to topics_path, success: "投稿に成功しました"
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end

  def destroy
      topic = Topic.find_by(id: params[:id])

      if topic.destroy
        redirect_to topics_path, success: "投稿を削除しました"
      else
        redirect_to topics_path, danger: "投稿の削除に失敗しました"
      end
  end

      private
    def topic_params
      params.require(:topic).permit(:image, :description)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      log_in @user
      redirect_to topics_path,success: "登録が完了しました"
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end
  
end

  private
  def log_in(user)
    session[:user_id] = user.id
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  
  def logged_in?
    !current_user.nil?
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </head>

  <body>
    <% flash.each do |key,value| %>
    <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>

    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to("/topics") do %>
          <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to favorites_index_path, :data => {:toggle => "tooltip", :placement => "bottom" }, :class => "btn btn-secondary", :title => "お気に入り一覧"  do %>
                <%= image_tag "icons/heart.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to new_topic_path, :data => {:toggle => "tooltip", :placement => "bottom" }, :class => "btn btn-secondary", :title => "投稿" do %>
                <%= image_tag "icons/camera.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to rooms_show_path, :data => {:toggle => "tooltip", :placement => "bottom" }, :class => "btn btn-secondary", :title => "ダイレクトメッセージ"  do %>
                <%= image_tag "icons/DM.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete, :data => {:toggle => "tooltip", :placement => "bottom" }, :class => "btn btn-secondary", :title => "ログアウト"  do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path, :data => {:toggle => "tooltip", :placement => "bottom" }, :class => "btn btn-secondary", :title => "新規登録"  do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path, :data => {:toggle => "tooltip", :placement => "bottom" }, :class => "btn btn-secondary", :title => "ログイン"  do %>
                <%= image_tag "icons/login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= yield %>
    <script>
    $(function(){
      $(".alert").fadeOut(5000);
    });
    
    $(function () {
  $('[data-toggle="tooltip"]').tooltip()
    });
  </body>
</html>

app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

app/views/pages/index.html.erb
<div class=" top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Make You Happy</h1>
    <h2 class="text-white">pictgram is service that you can post photos.</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to "Sign in",new_user_path,class:"btn btn-block btn-white"%>
      </div>
      <div class="col-md-3">
        <%= link_to "Log in",login_path,class:"btn btn-block btn-white"%>
      </div>
    </div>
  </div>
</div>